name: 'Parse Semver'
description: 'Parses a semantic version from a given string'
inputs:
  input_string:
    description: 'Raw input string containing or is a semantic version to be parsed'
    required: true
  version_extractor_regex:
    description: 'Regex to extract semantic version from a raw input string if input string is not a semver'
    required: false
    default: ''
outputs:
  major:
    description: 'MAJOR part of the semver'
  minor:
    description: 'MINOR part of the semver'
  patch:
    description: 'PATCH part of the semver'
  prerelease:
    description: 'PRERELEASE part of the semver'
  build:
    description: 'BUILD part of the semver'
  fullversion:
    description: 'Full representation of the semver'
runs:
  using: 'node12'
  main: 'index.js'