name: Pull Request Labels
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    if: github.base_ref == 'master' || github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: "bump:major,bump:minor,bump:patch"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
